### PR TITLE
Hbridge

### PR DESCRIPTION
**Pull request by janaifx**
Infineon board_2

### CODE REVIEW

**Comment by janaifx** [comment]
@KjellMorgenstern i have added one more board. kindly approve and make it visible in Fritzing tool

**Comment by KjellMorgenstern** [comment]
@janaifx Please do not commit unrelated files.

**Comment by janaifx** [comment]
@KjellMorgenstern can you please give me more info? what do you mean by unrelated files?
and please let me know what file is added...

**Comment by KjellMorgenstern** [comment]
Just scroll to the top and click "Files changed". Maybe this tutorial can help: https://youtu.be/1XrP6POUPD0?si=KT1nsqZ0Oik5L-i9

**Comment by janaifx** [comment]
@KjellMorgenstern will take care in future. Anything to be done from my side for this request #384

**Comment by KjellMorgenstern** [comment]
@janaifx What do you mean?

**Comment by janaifx** [comment]
@KjellMorgenstern do i need to remove those files and commit it again?

**Comment by janaifx** [comment]
@KjellMorgenstern any update here? Board is still not published in Fritzing tool...

**Comment by janaifx** [comment]
@KjellMorgenstern ...do we have any update...

**Comment by KjellMorgenstern** [comment]
@janaifx I have fixed several remaining issues and added the H-Bridge to the develop branch.

Due to various merges, there was a conflict merging this branch, which I resolved executing a git merge --squash .
Please check my changes, and open a new merge request based on the develop branch if there are further changes.

**Comment by janaifx** [comment]
@KjellMorgenstern Happy new year :)

I see Hbridge #384 request is closed, but still not reflecting in Fritzing tool.
kindly do the needful and let me know anything to be done from my side.

Thanks in advance...

**Comment by KjellMorgenstern** [comment]
Which version of Fritzing did you try?

image

**Comment by janaifx** [comment]
I'm using Version 1.0.0

**Comment by KjellMorgenstern** [comment]
This was integrated with version 1.0.2.

**Pull request closed without merging**
