### PR TITLE
add Arduino sensor shield V5, gear-motor, ky_006, shaft-encoder, yl99 parts

### PR DESCRIPTION
**Pull request by vanepp**
I seem to be behind the master again, and this won't automatically merge. This adds the above five parts to core. I loaded the local parts repository in to Fritzing, regenerated the database and checked the parts all load correctly.

### CODE REVIEW

**Comment by KjellMorgenstern** [comment]
The conflict is because the FIRST parts on your branch have different icons (I compressed the svg  icon files during the pull request). There are many ways to recover, one would be to reset your feature branch to origin/develop, then cherry-pick 37cd8f9. Command line looks like this

```
# first make sure we are in sync
git fetch --all
# save uncommited changes, just to be save
git stash
```

A short command to resolve the conflict:
` git rebase --onto origin/develop develop~1 develop`
This says: take my last commit from the branch 'develop', append it to origin/develop, and then set 'develop' to point there. After this is done, you can push (using force) the new develop branch to github, and this pull-request will be updated.

Or a long way, maybe easier to understand, split in single steps:

```
# go to your develop branch
git checkout develop
# create 'temp' 
git checkout -b temp
# go back from temp to develop
git checkout develop
# set your develop branch to the official one from github
git reset --hard origin/develop
# now the cherry picking
git cherry-pick temp

```



```
# finished, check that all is ok and push to github/vanepp/fritzing-parts. Force will be needed.
git push --force
```

This is blind flight, as I don't know your local files structure. It's always a good idea to check that you don't have any uncommited changes (and stash or commit them) before doing such things.

**Comment by vanepp** [comment]
I'm doing this from the cygwin command line in Win7 with a locally cloned version of my Fritzing-parts repository on github. I think the part I have been missing is the git fetch --all, I have tried git pull but that usually tells me I am up to date (I think with my fork on github which makes sense). The last time I synced my repo to the master I did it via the github web page with a trick from stackoverflow (I think the usual way is via a git client running on the local machine, although I haven't seen an example of that either.) and that seemed to work. I forgot to do that this time, but if the git fetch --all works (as it seemed to) then that is probably the correct way to do this. If I can figure out a procedure that works I'll write it up and post it to the forums as a howto as I think this is what is stopping a lot of folks from submitting parts. Here is a log from my local machine from the cygwin command line:

cd /cygdrive/d/repos/fritzing-parts

git fetch --all

Fetching origin
Fetching upstream
From https://github.com/vanepp/fritzing-parts
 * [new branch]        Nitaym-frc-parts   -> upstream/Nitaym-frc-parts
 * [new branch]        arduino-logo       -> upstream/arduino-logo
 * [new branch]        develop            -> upstream/develop
 * [new branch]        generic-smd        -> upstream/generic-smd
 * [new branch]        gh-pages           -> upstream/gh-pages
 * [new branch]        minify_icons       -> upstream/minify_icons
 * [new branch]        nightlyParts       -> upstream/nightlyParts
 * [new branch]        revert-195-xml-fix -> upstream/revert-195-xml-fix
 * [new branch]        test               -> upstream/test
 * [new branch]        travis             -> upstream/travis

$git stash    (shouldn't do anything as there are no uncommited changes.)

No local changes to save

$ git rebase --onto origin/develop develop~1 develop
First, rewinding head to replay your work on top of it...
Fast-forwarded develop to origin/develop.

$ git push -f
Username for 'https://github.com':
Password for 'https://vanepp@github.com':
Everything up-to-date

The changes appear to be in  the local repo:

$ ls /cygdrive/d/repos/fritzing-parts/core/Sensor-Shield-v5_1.fzp
/cygdrive/d/repos/fritzing-parts/core/Sensor-Shield-v5_1.fzp

$ ls /cygdrive/d/repos/fritzing-parts/svg/core/breadboard/Sensor-Shield-v5_1_breadboard.svg
/cygdrive/d/repos/fritzing-parts/svg/core/breadboard/Sensor-Shield-v5_1_breadboard.svg

ls /cygdrive/d/repos/fritzing-parts/svg/core/icon/Sensor-Shield-v5_1_icon.svg
/cygdrive/d/repos/fritzing-parts/svg/core/icon/Sensor-Shield-v5_1_icon.svg

ls /cygdrive/d/repos/fritzing-parts/svg/core/pcb/Sensor-Shield-v5_1_pcb.svg
/cygdrive/d/repos/fritzing-parts/svg/core/pcb/Sensor-Shield-v5_1_pcb.svg

ls ls /cygdrive/d/repos/fritzing-parts/svg/core/schematic/Sensor-Shield-v5_1_schematic.svg
/cygdrive/d/repos/fritzing-parts/svg/core/schematic/Sensor-Shield-v5_1_schematic.svg

but somehow it doesn't seem to have pushed the changes as it should both from the upto date  message from the push and that nothing has changed in the pull request. As well my repo on github is still unhappy, so I think the git fetch -all may not have worked somehow my forked repo shows
the same message as it did last night:

https://github.com/vanepp/fritzing-parts

This branch is 23 commits ahead, 23 commits behind fritzing:develop.

...
vanepp Arduino sensor shield V5, gear-motor, ky_006, shaft-encoder, yl99 parts 

I think the problem here is getting my fork synced to the master correctly, despite the output from the git fetch --all, which looked like it should have done it, it doesn't seem to have updated my repo. I'm not sure how to do that other than the stackoverflow method using the github web page. I'd rather find the appropriate command line method to do that so I can do it entirely from the local cygwin command prompt if that is possible (which I expect it is if I knew how).

**Comment by KjellMorgenstern** [comment]
When you ran `git push -f` , where you on the develop branch? If you are on a different branch, it would try to push that one. You can checkout a specific branch with the command `git checkout <branchname>`

**Comment by vanepp** [comment]
Yep. This from the session just after the  push -f
$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean

As far as I can see the problem seems to be that my fork on github isn't synced with the master at https://github.com/fritzing/fritzing-parts since the github web page on my parts fork thinks my fork is 25 commits behind master and 25 commits ahead of it (presumably my pull request) but as usual I'm not sure. Is there anything I can run either from my machine or the web page for my repo on github that will tell you anything useful? I was hoping the

$ git fetch --all
Fetching origin
Fetching upstream
From https://github.com/vanepp/fritzing-parts
...

meant origin is my fork on github and upstream was https://github.com/fritzing/fritzing-parts, but perhaps that is wrong, and origin is my local repo and upstream is my fork on github and the main repository was never accessed as that would match what I'm seeing which is that my local repo matches my fork on github, but neither of them match the main repository. I see that after I manually synced my fork the last time and then cloned it locally I did a 

git remote add upstream https://github.com/fritzing/fritzing-parts.git

which I assume is still there. That was in one of the web pages on making git work that I read trying to figure out what I'm doing wrong. With that in place I was able to do

git fetch upstream pull/141/head:pr-141

to download a pull request (for the first parts I think) to work on. So in theory upstream should be the main repository I think, it just doesn't seem to be updating correctly somehow. As usual github baffles me!

**Comment by KjellMorgenstern** [comment]
Which remote points to your fork https://github.com/vanepp/fritzing-parts, is it 'origin' or 'upstream' ? 
And maybe you have called you local 'develop' branch differently, for example 'vanepp-develop'?
Assuming both is true, the command would then be used with those different names:

git rebase --onto upstream/develop vanepp-develop~1 vanepp-develop

To update the pull request, you must update the branch you created the pull request from, not the branch you are requesting to pull to (usually you do not have write access to that one, or should not directly push there, that is the idea of the pull request)

**Comment by vanepp** [comment]
That may have revealed the problem. Had to  dig up the command to display the remotes:

$ git remote -v
origin  https://github.com/vanepp/fritzing-parts.git (fetch)
origin  https://github.com/vanepp/fritzing-parts.git (push)
upstream        https://github.com/vanepp/fritzing-parts.git (fetch)
upstream        https://github.com/vanepp/fritzing-parts.git (push)

Which may be where my problem is. origin and upstream are both my repo. I'll change upstream to

https://github.com/fritzing/fritzing-parts.git

and try again and see if things improve.

**Comment by vanepp** [comment]
At this point I think I have managed to get my fork synced to the master, but this pull request is still broken. I'll try closing this pull request and redo it from the now hopefully synced repo and see if that works better.

**Pull request closed without merging**
