### PR TITLE
Fix xml errors in part definitions.

### PR DESCRIPTION
**Pull request by jensh**
Removed some duplicate attributes and added some missing spaces.

scripts/genmoduleidfzphash.py: xml.dom.minidom.parse() had problems with them.

### CODE REVIEW

**Comment by jensh** [comment]
i revert the changes in obsolete.

**Comment by KjellMorgenstern** [comment]
Sorry, I overlooked, PR should go to nightlyparts, not directly to master. I reverted the change and created a new PR

**Comment by KjellMorgenstern** [comment]
Fix was now merged with #196 to nightlyparts , no conflicts. Also, I updated the settings, so nightlyparts is the github default. Sorry about the mixup.

**Comment by vanepp** [comment]
"Looks good to me, but I wouldn't touch anything in the 'obsolete' folder. @vanepp What do you think about this?" I agree that modifying the obsolete folder might not be wise. I don't entirely understand how the obsolete mechanism works and how sensitive it is to changes in previous xml. Otherwise the changes are good, as they change technically wrong xml (which Fritzing accepts) in to correct xml.

**Pull request merged**
